restartPolicy: Always

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
    http_2xx_ssl:
      prober: http
      timeout: 5s
      http:
        valid_status_codes: [] #Defaults to 2xx
        method: GET
        fail_if_ssl: false
        fail_if_not_ssl: true
