alertmanager:
  nodeSelector:
    region: node

  ## Persist storage

  # storageSpec:
  #   volumeClaimTemplate:
  #   # - metadata:
  #   #     name: alertmanager-db
  #     spec:
  #       storageClassName: gp2
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi

  config:
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      group_by: ['cluster', 'alertname', 'service']

      # The child route trees
      routes:
      # Do not alert on warning
      - match:
          severity: warning
        receiver: 'null'

    # Inhibition rules allow to mute a set of alerts given that another alert is
    # firing.
    # We use this to mute any warning-level notifications if the same alert is 
    # already critical.
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'null'


prometheus:

  ## How long to retain metrics for
  # retention: 15d

  nodeSelector:
    region: node
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Gi
      selector: {}

  ## Scrape various services
  serviceMonitors:

    ## Scrape Openshift router
    # - name: openshift-router
    #   labels:
    #     app: openshift-router
    #     prometheus: prometheus-test
    #   selector:
    #     matchLabels:
    #       router: router
    #   endpoints:
    #     - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    #       interval: 15s
    #       port: 1936-tcp
    #       scheme: http
    #   namespaceSelector:
    #     any: true

    ## Scrape Mysql exporter
    # - name: mysql-exporter
    #   labels:
    #     prometheus: prometheus-test
    #   selector:
    #     matchLabels:
    #       app: prometheus-mysql-exporter
    #   endpoints:
    #     - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    #       # Increasing interval and scrapeTimeout as it was taking up to 1m to get back
    #       interval: 5m
    #       scrapeTimeout: 5m
    #       scheme: http
    #   namespaceSelector:
    #     any: true

  ## Prometheus alert rules
  # prometheusRules:
  #   - name: alert.rules
  #     rules:
  #     - alert: ProbeHealth
  #       expr: probe_success < 1
  #       for: 5m
  #       annotations:
  #         description: Probe is failing

grafana:
  nodeSelector:
    region: node
  storageSpec:
    class: gp2
    accessMode: "ReadWriteOnce"
    resources:
      requests:
        storage: 10Gi
    selector: {}
  
  ## Custom dashboard list
  # serverDashboardConfigmaps: {}

  ## Keep the Dashboards that are defined in this HELM chart
  keepOriginalDashboards: false

  ## Disable anonymous auth
  auth:
    anonymous:
      enabled: "false"
  adminUser: "admin"
  adminPassword: "admin"

deployKubelets: true
deployKubeScheduler: false
deployKubeControllerManager: false
deployCoreDNS: false
deployKubeDNS: false
deployKubeEtcd: false